[mackerel]
build_path = "_build"
build_suffix = ".html"
content_path = "content"
doc_suffix = ".md"
template_path = "templates/starter"
template_suffix = ".html"
content_renderer = "MarkdownRenderer"
template_renderer = "Jinja2Renderer"
navigation = [
    { label = "Home", url = "/", children = [] },
    { label = "About", url = "/about.html", children = [] },
    { label = "Posts", url = "/posts/", children = [] },
]

[MarkdownRenderer]
output_format = "html"
extensions = [
    "markdown.extensions.meta",
    "markdown.extensions.extra",
]

[Jinja2Renderer]
trim_blocks = true
lstrip_blocks = true

[user]
title = "Mackerel"
description = "A minimal starter site."
copyright = "MIT License © 2025"
powered = "https://mackerel.sh"
