__version__ = '0.2'
__title__ = 'Mackerel'
__description__ = 'Minimal static site generator built with type annotations'
__author__ = 'Paris Kolios'
__author_email__ = 'paris@enc.io'
__url__ = 'http://mackerel.sh'
__license__ = 'MIT'
__copyright__ = 'Copyright 2017 Paris Kolios'
